[project]
name = "senate-disbursements"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyyaml>=5.1",
    "requests>=2.32.5",
]
